### PR TITLE
Implemented UI changes and fixed Viewer Scroll Exception

### PR DESCRIPTION
**Pull request by Arjun-Sur**

### CODE REVIEW

**Comment by Arjun-Sur** [comment]
[Highlight currently selected DCM file](https://trello.com/c/scCLcmWs/23-highlight-currently-selected-dcm-file)

**Comment by Arjun-Sur** [comment]
[Support for zip-files](https://trello.com/c/GTKkrok5/25-support-for-zip-files)

**Comment by Arjun-Sur** [comment]
[Viewer Scroll Exception](https://trello.com/c/ZI2jAanj/20-viewer-scroll-exception)

**Comment by Arjun-Sur** [comment]
[The current/selected file isn't always shown properly](https://trello.com/c/BbdnHT9D/26-the-current-selected-file-isnt-always-shown-properly)

**Review by sslampa — APPROVED** [review]
This looks good to me!

**Pull request merged**
